### ISSUE TITLE
Feature to use glib-rs instead of gettext-sys

### ISSUE THREAD

**Issue by Vypo** [Koka/gettext-rs#58]
I'd like to use gettext for internationalization in a GTK application. glib (and glib-rs) exposes some of the gettext API. Would it be possible to piggyback on that interface for gettext-rs, and if so, would exposing a feature in gettext-rs make sense?

[relevant glib docs](https://developer.gnome.org/glib/stable/glib-I18N.html)

[relevant glib-rs docs](https://docs.rs/glib/0.10.3/glib/fn.dgettext.html)

**Comment by Minoru** [comment]
Oh, interesting! I wasn't aware that GLib provides its own wrappers. I thought GTK applications use native gettext.

After looking at the docs you linked, I don't think glib-rs can replace gettext-sys, because glib-rs doesn't expose `textdomain`, `bindtextdomain`, and `bind_textdomain_codeset` functions. Without those, the program will work correctly only in certain locales, and only if the default gettext paths happen to include the installation directory of the program's message catalogues.

Furthermore, glib functions provide additional checks to see if the message should be translated or not. At a glance, I can't tell how exactly they change the semantics, but I think that mere presence of those checks make glib functions different from "pure gettext". In other words, we probably can't build gettext-rs on top of glib-rs.

Overall glib-rs looks like an alternative to gettext-rs, not to gettext-sys: both provide safe APIs, but glib-rs uses its own `GString` and integer types where gettext-rs uses Rust types. If gettext-rs were to wrap glib-rs, we'd just introduce additional conversions from `*const c_char` to `GString` to `String` for no good reason.

It looks to me that a GTK application would need to use gettext-rs for the aforementioned three functions, and then use glib-rs for `g_*gettext` functions. Are you doing that already? Are there any pain points that made you open this issue?

**Comment by Vypo** [comment]
My biggest concern (and it's speculative) is that I'll end up with two copies of gettext compiled/linked in, possibly with different versions.

The glib-rs functions are slightly less ergonomic, but that's a minor point.

**Comment by Minoru** [comment]
It doesn't look like glib-rs bundles gettext, so you should be fine ;) Also, I searched their issue tracker and it looks like they recommend using gettext-rs to call the three aforementioned functions (https://github.com/gtk-rs/gtk-rs/issues/112, https://github.com/gtk-rs/gtk-rs/issues/330 ) — which to me suggests that they have this use-case in mind and don't see a problem with it.

**Comment by Minoru** [comment]
@Vypo, so, where did you end up with? You're using `gettext-rs` to configure gettext, and then use `glib-rs` to get the localized messages? I'd like to know if there's something that should be done on the gettext-rs side, or if this issue can be closed now.

**Comment by Vypo** [comment]
I'm using gettext-rs for translations, and haven't touched the glib wrapper yet, and I haven't tried building on windows/osx so far. Don't need anything specific from gettext-rs yet!

**Comment by Minoru** [comment]
Okay. I'll close the issue then, and if something specific comes up, please open a new one and we'll see what gettext-rs can do for you. Cheers!
